version: '3'
services:
  apigateway:
    image: anjeonghoo/apigateway
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://127.0.0.1:8761/eureka/
    ports:
      - 8888:8888
    networks:
      - msa-network

  eureka:
    image: anjeonghoo/eureka
    ports:
      - 8761:8761 # Eureka 서비스 포트 설정
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
